* BULK
** Trade-off
   - transparency :: as good as Lisp
   - syntax complexity :: better than most Lisps
   - generality :: better than Lisp (stores arbitrary bytes without escaping)
   - extensibility :: TODO
   - decentralization :: only decentralized binary format? on par with plain text formats using
     decentralized IDs (like URI based on decentralized DNS)
   - discoverability :: TODO
   - compactness :: better than all general binary formats because they lack abstraction, worse
     than any ad hoc format (like ASN1)
   - processing speed :: extremely simple to parse
     - easy to evaluate
     - possible to forbid evaluation for extremely restricted environments (embedded)
   - processing footprint :: TODO

** Syntax

   | marker | shape             | notes                  |
   |--------+-------------------+------------------------|
   | 00     | nil               |                        |
   | 01     | (                 |                        |
   | 02     | )                 |                        |
   | 03     | # Nat {content}   |                        |
   | 04–0F  | reserved          |                        |
   | 10–7F  | refs              |                        |
   | 80–BF  | w6[value]         | value = (marker && 3F) |
   | C0–FF  | #[size] {content} | size = (marker && 3F)  |
   |        |                   |                        |

** BULK core namespace
   NSID: 0x10

   - 0x00 :: =( version Nat Nat )=
   - 0x01 :: =import=
     - =( import {marker}:Nat ( namespace {id}:Expr ) )=
     - =( import {base}:Nat ( package {id}:Expr {count}:Nat ) )=
   - 0x02 :: =namespace=
   - 0x03 :: =package=
   - 0x04 :: =( define {thing}:Expr Expr )=
     - =( define ( namespace {id}:Expr {marker}:Nat ) {defs}:Bytes )=
     - =( define ( package {id} ) {namespaces}:Bytes )=
     - =( define Ref {value}:Expr )=
   - 0x05 :: =( mnemonic {thing}:Expr {mnemonic}:String )=
     - =( mnemonic ( namespace {marker}:Nat ) {mnemonic}:String )=
     - =( mnemonic Ref {mnemonic}:String )=
   - 0x06 :: =( explain {thing}:Expr {doc}:Expr )=
   - 
   - 0x07 :: =string=
     - =( string Bytes )=
     - =( string Encoding Bytes )=
     - =( define string Encoding )=
   - 0x08 :: =( iana-charset Nat ):Encoding=
   - 0x09 :: =( bulk Bytes )=
   - 0x0A :: =( blob Bytes )=
   - 
   - 0x0B :: =( concat {a1} {a2} )=
   - 0x0C :: =( indexed-bulk Expr Expr )=
   - 0x0D :: =indexed-array=
     - =( indexed-array Expr Expr Expr )=
     - =( indexed-array Expr Expr )=
   - 
   - 0x0E :: =true=
   - 0x0F :: =false=
   - 
   - 0x10 :: ( subst {code} )
   - 0x11 :: ( arg Nat )
   - 0x12 :: ( rest Nat )
   - 0x13 :: =( values {exprs} )=
   - 
   - 0x14 :: =( unsigned-int Bytes ):Nat=
   - 0x15 :: =( signed-int Bytes ):Int=
   - 0x16 :: =( fraction Int Int )=
   - 0x17 :: =( binary-float Bytes )=
   - 0x18 :: =( decimal-float Bytes )=
   - 0x19 :: =( binary-fixed Nat Bytes )=
   - 0x1A :: =( decimal-fixed Nat Bytes )=
   - 
   - 0x1B :: =prefix=
     - =( prefix {bytecode} )=
   - 0x1C :: =postfix=
     - =( postfix {bytecode} )=
   - 0x1D :: =arity=
     - =( define ( arity {contexts} ) {arities} )=
       - ={contexts}= can contain =prefix=, =postfix=, or any other reference
       - ={arities}= is a sequence of expressions that can be shaped:
	 - =nil= meaning all known arities should be forgotten
	 - =( {kind}:Expr {target} )=
	   - if ={kind}= is =nil=, it sets all references designated by ={target}= as operands
	   - if ={kind}= is typed =Nat=, it sets all references designated by ={target}= as
             operators of arity ={kind}=
	   - if ={target}= is =nil=, it designates all references with unknown arity
	   - if ={target}= is a sequence of references, it designates each of those

** BULK utils
   - decimal2 :: =( subst ( decimal-fixed 2 ( arg 0 ) ) )=
   - property-list :: =( subst ( values ( define ( arity prefix ) nil ( 1 nil ) ) ( prefix
     ( rest 0 ) ) ) )=

** BARK: BULK Archive
   When needed, metadata can be any expression (=nil= SHOULD be used to indicate no metadata).

   When reading expressions as entries, ignore =nil= and process =description= forms. Entries and
   descriptions both are numbered (not =nil=).

   - =bark= (=EagerFunction=)
   - =( described {metadata}:Expr {content}:Expr )=
     - ={content}= can be an array (e.g. a file's content) or BULK expression
   - =( description {metadata} )=
     - can be inserted in many places in a BULK stream to annotate virtually anything
     - can be used to group metadata expressions
   - =( about {what} )=
     - ={what}= is a sequence of identifiers, each identifying a subject of the metadata
     - if there are N subjects, it is equivalent to N metadata forms each with one subject (it is
       important for metadata like RDF where there is a notion of base URI)
   - =( identified {ids} )=
     - ={ids}= is a sequence of identifiers, each identifying the subject of the metadata
     - an array as identifier is only valid within the BARK archive (and could be used as fragment
       identifier)
     - a =(bark:hash {hash} )= form as identifier is a global content-adressing identifier
   - =next=
     - as identifier, designates the first expression in the scope of the metadata form
   - =( comment Expr )=
   - =( path {components} ):Path=
     - by design, there is no way to express an absolute FS path
       - an application is free to define insecure forms to express absolute paths and links
       - what if a component contain "/"?
	 - implementation should not resolve the name but look it up in the directory entries
           (that takes care of "/" but not of a ".." entry, this still needs checking, shame on
           Unix)
   -
   - =( compressed {method}:Expr {content}:Expr )=
   - =deflate=
   - =deflate64=
   - =lzma=
   - =lzma2=
   - =bz2=
   - =lzw=
   - =lzo=
   - =( hash {signature}:Expr )=
   - =( encrypted {method}:Expr Bytes )=
   - tar-inspired semantics
     - metadata
       - =( user {id}:Expr )=
	 - ={id}= can be anything, incl. string and Nat
	   - can appear multiple times
	     - e.g. "pierre"/1000:
	       - =( user ( string "pierre" ) )=
	       - =( user 1000 )=
       - =( group {id}:Expr )=
       - =( accessed {time} )=
       - =( modified {time} )=
       - =( changed {time} )=
       - =( mode {mode} )=
       - =( posix-acl {acls} )=
	 - =( user {id} {mode} {default?} )=
	 - =( group {id} {mode} {defaults?} )=
	 - =( other {mode} {defaults?} )=
	 - =( mask {mode} {defaults?} )=
       - =( xattr {xattr} )=
	 - ={xattrs}= is a property list of ={name} {value}=
     - entry
       - an array as an entry is presumed to be a regular file
       - =( hard-link Path )=
       - =( sym-link Path )=
       - =( char-dev {major}:Nat {minor}:Nat )=
       - =( block-dev {major}:Nat {minor}:Nat )=
       - =directory=
       - =fifo=
       - =( sparse-file {segments} )=
	 - Bytes
	 - =( hole {size}:Nat )=
	   - ={size}= in bytes
   - tar-specific
     - =contiguous=
   - gzip-specific (cf. [[https://datatracker.ietf.org/doc/html/rfc1952][RFC 1952]])
     - =( ascii-text Boolean )=
     - =( os Expr )=
       - other vocabularies may provide additional expressions for OSes
       - =fat=
       - =amiga=
       - =vms=
       - =unix=
       - =vm/cms=
       - =atari=
       - =hpfs=
       - =macintosh=
       - =z-system=
       - =cp/m=
       - =tops-20=
       - =ntfs=
       - =qdos=
       - =acorn=
       - =unknown=
     - =maximum-compression=
     - =fastest-compression=
     - =( extra-field {subfield-id}:Bytes Bytes )=
     - ( cpio-compressed Bytes )
   - dar-inspired semantics
     - split archives
       - advertised in container metadata
	 - archive's ID
	 - members' IDs
     - FS-specific attributes
     - incremental backup?
     - fast member extract? (how does DAR does that?)

*** BARK archive (.bark)
    A =foobar.bark= archive with multiple files:

    #+BEGIN_SRC bulktext
      bark
      ( described
	( metadata ( path "foo.txt" ) )
	( compressed lzma {foo.txt}:Bytes ) )
      ( described
	( metadata ( path "bar.jpg" ) )
	{bar.jpg}:Bytes )
    #+END_SRC

    A =foo.txt.bark= archive with a single file and hash for integrity:

    #+BEGIN_SRC bulktext
      bark
      ( described
	( metadata ( path "foo.txt" )
		   ( hash ( sha3 {hash}:Bytes ) ) )
	( compressed lzma {foo.txt} ) )
    #+END_SRC

    A =manifest.bark= manifest about other files:

    #+BEGIN_SRC bulktext
      bark
      ( description
	( metadata ( about ( path "foo.txt" ) )
		   ( hash ( md5 {hash}:Bytes ) ) ) )
      ( description
	( metadata ( about ( path "bar.txt" ) )
		   ( hash ( md5 {hash}:Bytes ) ) ) )
      ( description
	( metadata ( about ( path "baz.iso" ) )
		   ( hash ( sha3 {hash}:Bytes ) ) ) )
    #+END_SRC

*** BARK utility
    #+BEGIN_EXAMPLE
    $ bark list <file>
    $ bark check <file>
    $ bark extract <file> [<members>]
    #+END_EXAMPLE

**** convert
     #+BEGIN_EXAMPLE
     $ barf convert --to gzip <file>
     $ barf convert --from dar <file>
     #+END_EXAMPLE

     This command convert from and to BULK. Converting to and then from BULK should produce a file
     at least semantically identical, (it may be bytewise identical, and it might be an
     implementation goal to achieve that, but no metadata is stored to that end by default).

     - mode of operation
       - lossless :: refuse conversion if semantic information would be lost (i.e. if a string is
         not encodable in the target format, but not if random padding is present)
       - lossy :: not lossless (i.e. a one-member tar archive converted to BULK might then be
         converted to gzip, at the price of losing ACLs)
       - transform :: change data representation to fit target format (i.e. if target is gzip, LZMA
         data would be recompressed to deflate, a UTF-8 string encoded in ISO-8859-1)
       - maintain :: refuse conversion if data representation in the source format doesn't fit
         target format
	 - should never need to refuse if BULK is target?
       - default is *lossless transform*

     Targets:
     - manifests
       - [[https://en.wikipedia.org/wiki/Simple_file_verification][SFV]]
       - md5sum
       - sha1sum
     - compression formats

*** Comparison
    - tar
      - +compression
    - zip
    - XZ
      - has a limited choice of compression/hash
    - gzip
    - cpio, pax

* Useful vocabularies
** BOON
   BULK's Own Object Notation

   BOON provides names to encode some common types of values found in JSON and formats with a
   semantics derived from it, like MessagePack or CBOR do. An expression that is one of BOON's
   cases has type =Boon=.

   BOON values can be:

   - associative maps :: =( boon:map {key/values} )= where ={key/values}= is a sequence of pairs of
     expressions where the first is a key and the second a value.
   - lists :: =( boon:list {values} )= where ={values}= is a sequence of expressions
   - scalars :: =nil=, =bulk:true=, =bulk:false=, numbers and strings are represented with the
     existing BULK syntax

   If values in maps and lists are only BOON values and if keys and strings are only UTF-8 strings,
   then an expression of type =Boon= also has type =Json=.

*** Reconciling BOON and JSON
    BOON can be used to encode data in a data model that is close to JSON's but more efficient and
    flexible. But in the same way that many applications already use JSON to encode a data model
    that doesn't completely fit JSON's, BULK's abstraction can be used to automatically reconcile
    BOON and JSON.

    For example, a card game that uses algebraic data types (like Haskell) or enums (like Rust) for
    cards could serialize a game state object in BOON in a way that mirrors exactly the game's data
    model:

    #+BEGIN_SRC lisp
      ( version 1 0 )
      ( import 20 ( package ( shake128 #[8] 0x00000000-00000000 ) 3 ) )
      ( game
	( boon:map
	  hands ( boon:map
		       player1 ( boon:list ( hearts 1 ) ( clubs king ) )
		       player2 ( boon:list ( diamonds jack ) ( clubs 10 ) ) )
	  turn player1
	  score ( boon:map
		       player1 87
		       player2 43 ) ) )
    #+END_SRC

    The same data would be far more verbose in JSON:

    #+BEGIN_SRC json
      {
	"type": "game",
	"hands": {
	  "player1": [{"suit": "hearts", "value": 1}, {"suit": "clubs", "value": "king"}],
	  "player1": [{"suit": "hearts", "value": 1}, {"suit": "clubs", "value": "king"}]
	},
	"turn": "player1",
	"score": {
	  "player1": 87,
	  "player2": 43
	}
      }
    #+END_SRC

    The BOON data weighs 46 bytes, of which 29 bytes are the version and import and 17 bytes are
    the actual data (in any use case where many game states would be serialized, either in a
    client/server exchange or in a game history record, those 29 bytes would be present only
    once). In comparison, the JSON data weighs 223 bytes. Readability can be traded off for size to
    bring down the JSON to 158 bytes, and some data can be encoded in strings rather than JSON
    objects, to get down to 100 bytes:

    #+BEGIN_SRC json
      {
	"type":"game",
	"hands": {
	  "pl1": [{"s": "♥", "v": 1},{"s": "♣", "v": "K"}],
	  "pl2": [{"s": "♥", "v": 1},{"s": "♣", "v": "K"}]
	},
	"turn": "p1",
	"score": {
	  "pl1": 87,
	  "pl2": 43
	}
      }
    #+END_SRC


    #+BEGIN_SRC json
      {
	"type":"game",
	"hands": {
	  "1": ["♥1", "♣K"],
	  "2": ["♥1", "♣K"]
	},
	"turn": 1,
	"score": {
	  "1": 87,
	  "2": 43
	}
      }
    #+END_SRC

    The interesting thing is that the package for the game namespace could provide a translation
    that automatically transform the BOON data into one of the two first JSON encodings.

    #+BEGIN_SRC lisp
      ( define card:game
	  ( subst ( boon:merge-maps ( boon:map "type" "game" ) ( arg 0 ) ) ) )
      ( define card:player1 "player1" )
      ( define hearts
	  ( subst ( boon:map "suit" "hearts" "value" ( arg 0 ) ) ) )
      ( define king "king" )
    #+END_SRC

** RDF 1.0

   - =( iri-reference String )=
   - =( base IRI )=
   - =rdf#= ⇔ =( iri-reference "[[http://www.w3.org/1999/02/22-rdf-syntax-ns#]]" )=
   - =blank=
     - =( blank {label}:String )=
   - =( literal {type}:IRIRef {dir}:Dir {lang}:LangTag {literal}:String )=
   - =( plain {lang}:LangTag {literal}:String )=
   - =( dir {dir}:Dir {lang}:LangTag {literal}:String )=
   - =( typed {type}:IRIRef {literal}:String )=
   - =ltr=, =rtl= (type: =Dir=)
   - =json= ⇔ =( rdf# "JSON" )=
   - =html= ⇔ =( rdf# "HTML" )=
   - =xml= ⇔ =( rdf# "XMLLiteral" )=
   - =( triples {triples} )=
   - =( turtle {statements} )=
   - =type= ⇔ =( rdf# "type" )=
   - =property= ⇔ =( rdf# "Property" )=
   - =statement= ⇔ =( rdf# "Statement" )=
   - =subject= ⇔ =( rdf# "subject" )=
   - =predicate= ⇔ =( rdf# "predicate" )=
   - =object= ⇔ =( rdf# "object" )=
   - =bag= ⇔ =( rdf# "Bag" )=
   - =seq= ⇔ =( rdf# "Seq" )=
   - =alt= ⇔ =( rdf# "Alt" )=
   - =value= ⇔ =( rdf# "value" )=
   - =list= ⇔ =( rdf# "List" )=
   - =nil= ⇔ =( rdf# "nil" )=
   - =first= ⇔ =( rdf# "first" )=
   - =rest= ⇔ =( rdf# "rest" )=
     
*** Differences between complete triples (3s) and turtle-like (Tl)
    In 3s, a single triple cannot cost less than 8 bytes:

    : (:A:B:C)

    For big graphs of mostly known references, this can already be a valuable
    improvement. {triples} could be a packed sequence without markers around triples, but that
    would mean that a single missing or superfluous expression would wreck everything that's after
    it. The fact that a triple is still a form limits the savings but keeps a level of robustness
    (but it would be possible to define a packing RDF form…).

    Adding another triple cannot cost less than adding 8 bytes:

    : (:A:B:C)(:A:B:D)

    In Tl, a standalone triple cannot cost less than 10 bytes:

    : (:A(:B:C))

    But adding another triple can cost as few as 2 bytes:

    : (:A(:B:C:D))

** XML
   XML is pretty complex, but most of it is unused (some even advised not to be used, i.e. unparsed
   entity). The vocabulary can be split into loosely coupled parts:

   - document
   - DTD
   - schema
   - Relax NG

*** Document
    XML content, not notation: no support for entities or CDATA. =string= can be used everywhere.

    : ( define ?rfc ( subst ( pi "rfc" ( rest 0 ) ) ) )

   #+BEGIN_SRC bulktext
     ( define ( namespace {id} 21 )
       ([ nil
	  ( mnemonic ( namespace 21 ) "xml" )
	  ( explain ( namespace 21 ) "This vocabulary can be used to represent XML data." )

	  ( define+ xml:xml10 "xml1.0" "( xml1.0 {content} )" )
	  ( define+ xml:xml11 "xml1.1" "( xml1.1 {content} )" )
	  ( define+ xml:pi "pi" "( pi {target} {content} )" )
	  ( define+ xml:comment "comment" "( comment {content} )" ) 
	  ( define+ xml:element "element" "( element {name} {content} )" )
	  ( define+ xml:attribute "attribute" "( attribute {name} {value} )" )
	  ( define+ xml:xml: "xml:" ( rdf:prefix "http://www.w3.org/XML/1998/namespace" ) )
	  ( define+ xml:xmlns: "xmlns:" "xmlns:" ( rdf:prefix "http://www.w3.org/2000/xmlns/" ) )
	  ( define+ xml:preserve "preserve" "preserve" ( attribute ( xml: "space" ) "preserve" ) ) ]) )
  
   #+END_SRC

*** Default  package?
    RDF + Simple XML ( + XPath )
** XPath namespace
   #+BEGIN_SRC bulktext
   ( verifiable-ns 0x1800 {id} nil "xpath"
   "This vocabulary can be used to represent XPath expressions."

   ( mnemonic/def nil "xpath" "( xpath {steps} )" )
   ( mnemonic/def nil "union" "( union {exprs} )" )
   ( mnemonic/def nil "step" "( step {axis} {test} {preds} )" )
   ( mnemonic/def nil "ancestor" nil )
   ( mnemonic/def nil "ancestor-or-self" nil )
   ( mnemonic/def nil "attribute" nil )
   ( mnemonic/def nil "child" nil )
   ( mnemonic/def nil "descendant" nil )
   ( mnemonic/def nil "descendant-or-self" nil )
   ( mnemonic/def nil "following" nil )
   ( mnemonic/def nil "following-sibling" nil )
   ( mnemonic/def nil "namespace" nil )
   ( mnemonic/def nil "parent" nil )
   ( mnemonic/def nil "preceding" nil )
   ( mnemonic/def nil "preceding-sibling" nil )
   ( mnemonic/def nil "self" nil )
   ( mnemonic/def nil "node()" nil )
   ( mnemonic/def nil "text()" nil )
   ( mnemonic/def nil "comment()" nil )
   ( mnemonic/def nil "pi()" "pi() or ( pi() {name}:String )" )
   ( mnemonic/def nil "pi()" nil )

   ( mnemonic/def nil "." "" ( step self node() ) )
   ( mnemonic/def nil ".." "" ( step parent node() ) )
   ( mnemonic/def nil "//" "" ( step descendant-or-self node() ) )

   ( mnemonic/def nil "step*" "" ( λ:lambda λ:a ( step λ:a node() ) ) )


   )
   #+END_SRC

   As a Step, {name}:QName ⇔ ( step child {name} ) ?

*** QName
    To maximize reuse between namespaces, URIRef and URIString expressions also have the type
    QName. Any Bytes whose content satisfy the NCName production also has.

** Dates namespace
   - Time = Date | TimeOfDay


   - =calendar-date=
     - =( calendar Nat )=
     - =( calendar Nat Nat )=
     - =( calendar Nat Nat Real )=
   - =week-date=
     - =( weekdate Nat )=
     - =( weekdate Nat Nat )=
     - =( weekdate Nat Nat Real )=
   - =( ordinal-date Nat Nat )=
   - =time-of-day=
     - =( time-of-day Nat )=
     - =( time-of-day Nat Nat )=
     - =( time-of-day Nat Nat Real )=
   - =( point-in-time Date TimeOfDay )=
   - =( zulu Time )=
   - =( offset TimeOfDay Time )=
   - =( years Nat Nat Nat Nat Nat Real )=
   - =( months Nat Nat Nat Nat Real )=
   - =( days Nat Nat Nat Real )=
   - =( hours Nat Nat Real )=
   - =( minutes Nat Real )=
   - =( seconds Real )=
   - =( weeks Nat )=
   - =( interval {exprs} ):Interval=
     - ={exprs}= is shaped =Time Time= | =Duration Time= | =Time Duration= | =Duration=
   - =repeat=
     - =( repeat Nat Interval )=
     - =( repeat Interval )=
   - =julian=
     - Julian Day Number :: =( julian Int )=
     - Julian Date :: =( julian Real )=
   - =anno-mundi=
     - =( anno-mundi Nat )=
     - =( anno-mundi Nat Nat )=
     - =( anno-mundi Nat Nat Real )=
   - =anno-hegirae=
     - =( anno-hegirae Int )=
     - =( anno-hegirae Int Nat )=
     - =( anno-hegirae Int Nat Real )=
   - =( unix-s Int )=
   - =( unix-ms Int )=
   - =( unix-ns Int )=
   - =( ntp Bytes )=
   - =( tai64 Bytes )=
   - =( tng-stardate Int Nat )=

** Hash
   #+BEGIN_SRC bulktext
     ( define ( namespace ( hash:shake128 {id} 20 ) ([ nil
      ( mnemonic ( namespace 20 ) "hash" )
      ( explain ( namespace 20 ) "The forms in this vocabulary can be used to represent hashes along with the hashing algorithm instead of using an unmarked byte sequence. When an algorithm has other inputs than the message, they can be provided after the hash itself as a property list.

     When an algorithm can produce hashes in different sizes and the size used is a number of bits divisible by 8, the size property should be omitted from the property list and inferred by the processing application from the size of the BULK expression (e.g. `( sha-3 #[48] {hash}:48B )` is a 384-bits SHA-3 hash).

     As a rule, each of these forms can contain `nil` as a first expression to denote not a hash but a choice of configuration in some application context. For example, `( uuid nil prepend {ns}:Bytes )` could mean that subsequent v3 and v5 UUIDs will be produced with {ns} as UUID namespace." )

      ( mnemonic hash:bsd "bsd" )
      ( explain hash:bsd "( bsd Bytes )" )
      ( mnemonic hash:sysv "sysv" )
      ( explain hash:sysv "( sysv Bytes )" )
      ( mnemonic hash:crc "crc" )
      ( explain hash:crc "( crc Bytes {config} ) `key` is the polynomial" )
      ( mnemonic hash:crc32 "crc32" )
      ( explain hash:crc32 "( crc32 Bytes )" )
      ( define hash:crc32 ( subst ( crc ( arg 0 ) key #[4] 0x04C11DB7 ) ) )
      ( mnemonic hash:fletcher "fletcher" )
      ( explain hash:fletcher "( fletcher Bytes {config} )" )
      ( mnemonic hash:adler32 "adler32" )
      ( explain hash:adler32 "( adler32 Bytes )" )

      ( mnemonic hash:uuid "uuid" )
      ( explain hash:uuid "( uuid Bytes {config} )" )
      ( mnemonic hash:md5 "md5" )
      ( explain hash:md5 "( md5 Bytes )" )
      ( mnemonic hash:sha1 "sha1" )
      ( explain hash:sha1 "( sha1 Bytes )" )
      ( mnemonic hash:sha2 "sha2" )
      ( explain hash:sha2 "( sha2 Bytes )" )
      ( mnemonic hash:sha3 "sha3" )
      ( explain hash:sha3 "( sha3 Bytes )" )
      ( mnemonic hash:shake128 "shake128" )
      ( explain hash:shake128 "( shake128 Bytes )" )
      ( mnemonic hash:shake256 "shake256" )
      ( explain hash:shake256 "( shake256 Bytes )" )
      ( mnemonic hash:blake2 "blake2" )
      ( explain hash:blake2 "( blake2 Bytes )" )

      ( mnemonic hash:size "size" )
      ( mnemonic hash:prepend "prepend" )
      ( mnemonic hash:append "append" )
      ( mnemonic hash:key "key" )
      ( mnemonic hash:salt "salt" ) ]) )
   #+END_SRC

** Encryption
   - blowfish?
   - camellia?
   - twofish?
   - AES?
   - serpent?
   - openpgp?

** TODO BULK Web Token
   Compare with CWT where claim keys are only documented in RFC, not CBOR, also CBOR cannot
   compactly express different versions of fields that take tags or not.

** Asking input
   - test https://github.com/eishay/jvm-serializers?

* [0%] Implementation notes
** TODO Semantics beyond definitions
   When implementing a processing application that gives semantics beyond the evaluation of
   expressions, to benefit from all possible evaluations, the application should just replace
   relevant prior definitions with its own implementation while evaluating the BULK streams.

** TODO Bad Unicode handling?
   https://www.tbray.org/ongoing/When/202x/2025/08/14/RFC9839

** TODO UBF
   https://github.com/ubf/ubf

** TODO [0%] Discovery
*** TODO Principle
*** TODO Security implications
* Minimal BULK
  : ( version 1 0 ) ( import ( package 20 ( hash:shake128 #[8] 8B ) 2 ) ) some:type #[0–63] {content}
  : |<---- 6 ---->| |<----------------------- 23 ---------------------->| |<----- 3 ----->|

  : ( version 1 0 ) ( import ( package 20 ( hash:shake128 #[8] 8B ) 2 ) ) some:type # {size} {content}
  : |<---- 6 ---->| |<----------------------- 23 ---------------------->| |<-- 3 -->| 2/3/5/9


  When a profile is known (like a specific file extension for typed blobs):

  : ( version 1 0 ) some:type #…
  : |<---- 6 ---->| |<- 2 ->|

  | content | array overhead | with profile | BULK overhead |
  |---------+----------------+--------------+---------------|
  | 63B     |              1 |            9 |            32 |
  | 255B    |            2+1 |           11 |            34 |
  | 65kB    |            2+2 |           12 |            35 |
  | 4GB     |            2+4 |           14 |            37 |
  | 18EB    |            2+8 |           18 |            41 |
  |         |                |              |               |

* The power of abstraction
** Explicit relationship between similar data
   When a protocol makes it possible to express several different data that are related but
   different in structure, most other formats can only express those relationships in human readable
   documentation.

   Example: an event format that includes information about the person doing the action and the
   person logging it:

   #+BEGIN_SRC json
     { "eventType": "WallPainted",
       "eventDate": "20210723T235601Z",
       "wallId": "d9e62839-dafe-49e1-b4d2-ce99c035fa9f",
       "logged": { "by": "alice", "date": "20210723T090145Z" },
       "painted": { "by": "bob", "date": "20210722T193545Z" }
     }
   #+END_SRC

   When the date for the action or logging is the same as the event, it might be omitted:

   #+BEGIN_SRC json
     { "eventType": "WallPainted",
       "eventDate": "20210723T235601Z",
       "wallId": "d9e62839-dafe-49e1-b4d2-ce99c035fa9f",
       "logged": { "by": "alice" },
       "painted": { "by": "bob" }
     }
   #+END_SRC

   And the fomat might include a shortcut for those cases:

   #+BEGIN_SRC json
     { "eventType": "WallPainted",
       "eventDate": "20210723T235601Z",
       "wallId": "d9e62839-dafe-49e1-b4d2-ce99c035fa9f",
       "loggedBy": "alice",
       "paintedBy": "bob"
     }
   #+END_SRC

   With almost all existing formats, there is not way to convey the relationship between =loggedBy=
   and =logged=.

   But in BULK, =loggedBy= can be explicitly defined in terms of =logged=:

   #+BEGIN_SRC bulktext
   ( verifiable-ns 0x1400 {id} nil "wall"
   "This vocabulary can be used to represent wall painting events."

   ( mnemonic/def nil "event" "( event {properties} )"
   ( mnemonic/def nil "type" "( type Expr )"
   ( mnemonic/def nil "date" "( date Expr )"
   ( mnemonic/def nil "wallId" "( wallId Expr )"
   ( mnemonic/def nil "logged" "( logged {properties} )"
   ( mnemonic/def nil "painted" "( painted {properties} )"
   ( mnemonic/def nil "by" "( by {person} )"
   ( mnemonic/def nil "wallPaintedEvent" "( wallPaintedEvent {properties} )" ( subst ( event ( type "WallPainted" ) ( rest 0 ) ) )
   ( mnemonic/def nil "loggedBy" "( loggedBy {person}:Expr )" ( subst ( logged ( by ( arg 0 ) ) ) )
   ( mnemonic/def nil "paintedBy" "( paintedBy {person}:Expr )" ( subst ( painted ( by ( arg 0 ) ) ) )
   #+END_SRC

   Which means that the application processing this format doesn't even need to know about
   =loggedBy= and =paintedBy= because BULK evaluation will transform them away:

   #+BEGIN_SRC bulktext
   ( wallPaintedEvent
     ( date "20210723T235601Z" )
     ( wallId #[16] 0xD9E62839-DAFE-49E1-B4D2-CE99C035FA9F )
     ( loggedBy "alice" )
     ( paintedBy "bob" ) )
   #+END_SRC

   will get evaluated into:

   #+BEGIN_SRC bulktext
   ( event
     ( type "WallPainted" )
     ( date "20210723T235601Z" )
     ( wallId #[16] 0xD9E62839-DAFE-49E1-B4D2-CE99C035FA9F )
     ( logged
       ( by "alice" ) )
     ( painted
       ( by "bob" ) ) )
   #+END_SRC
