name: Deploy on GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: JRMurr/direnv-nix-action@v4.2.0

    - name: Build spec
      run: make html txt
      
    - name: Upload static files as artifact
      id: prepare
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./
        
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
